import Head from 'next/head';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Xhek Sport Academy</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Hero heading='Xhek Sport Academy' message='Pasioni dhe deshira per perfeksion' />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
